# Generated by Django 4.2.2 on 2023-06-21 18:24

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, default='ERqD6cwQ9UQicUecSBA2kD', editable=False, max_length=22, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2048)),
                ('destroyLiveAfterSeconds', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=256)),
                ('destroyAfterDays', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
